apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenwebappdeployment
  namespace: moback-ns
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 60
  selector:
    matchLabels:
      app: mavenwebapp
  template:
    metadata:
      name: mavenwebapppod
      labels:
        app: mavenwebapp
    spec:
      containers:
        - name: mavenwebappcontainer
          image: tarunnagb/maven-web-application:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mavenwebappsvc
  namespace: moback-ns
spec:
  selector:
    app: mavenwebapp
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
